import React, { useState } from 'react';
import { CalendarPost } from '../types';
import { CopyIcon, CheckIcon, DownloadIcon } from './Icons';

interface CalendarViewProps {
  posts: CalendarPost[];
  topic: string;
}

const CalendarView: React.FC<CalendarViewProps> = ({ posts, topic }) => {
  const [copied, setCopied] = useState(false);

  const handleCopyAll = () => {
    const allContent = posts.map(p => 
      `Day ${p.day}: ${p.title}\n\n${p.content.split('\n').join('\n\n')}\n\n***\n`
    ).join('\n');
    
    navigator.clipboard.writeText(`Content Calendar: ${topic}\n\n${allContent}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPdf = () => {
    // We create a printable window
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert("Please allow popups to download the PDF");
      return;
    }

    const htmlContent = `
      <html>
        <head>
          <title>Content Calendar - ${topic}</title>
          <style>
            body { font-family: 'Georgia', serif; padding: 40px; color: #1a1a1a; max-width: 800px; margin: 0 auto; }
            h1 { text-align: center; color: #b45309; border-bottom: 2px solid #b45309; padding-bottom: 20px; margin-bottom: 40px; }
            .post-container { margin-bottom: 40px; page-break-inside: avoid; }
            .day-label { font-family: sans-serif; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 2px; color: #666; margin-bottom: 5px; }
            .post-title { font-size: 1.5rem; font-weight: bold; margin: 0 0 15px 0; color: #000; }
            .post-content { font-size: 1rem; line-height: 1.6; white-space: pre-wrap; }
            .footer { margin-top: 50px; text-align: center; font-size: 0.8rem; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
          </style>
        </head>
        <body>
          <h1>Karma Kitchen Marrakech: ${topic}</h1>
          ${posts.map(p => `
            <div class="post-container">
              <div class="day-label">Day ${p.day}</div>
              <h2 class="post-title">${p.title}</h2>
              <div class="post-content">${p.content}</div>
            </div>
          `).join('')}
          <div class="footer">Generated by Karma Kitchen AI</div>
          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  return (
    <div className="w-full animate-fade-in">
      {/* Toolbar */}
      <div className="flex flex-col sm:flex-row justify-between items-center mb-6 gap-4">
        <h2 className="text-2xl font-serif font-bold text-gray-800">
          <span className="text-orange-600">{posts.length}-Day</span> Calendar
        </h2>
        <div className="flex gap-3">
          <button
            onClick={handleCopyAll}
            className="flex items-center gap-2 px-4 py-2 bg-white/70 hover:bg-white rounded-xl shadow-sm border border-white/50 transition-all text-gray-700 font-medium"
          >
            {copied ? <CheckIcon className="w-5 h-5 text-green-600" /> : <CopyIcon className="w-5 h-5" />}
            <span>{copied ? 'Copied All' : 'Copy All'}</span>
          </button>
          <button
            onClick={handleDownloadPdf}
            className="flex items-center gap-2 px-4 py-2 bg-black text-white rounded-xl shadow-md hover:bg-gray-800 transition-all font-medium"
          >
            <DownloadIcon className="w-5 h-5" />
            <span>Download PDF</span>
          </button>
        </div>
      </div>

      {/* Grid View */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {posts.map((post) => (
          <div key={post.day} className="glass-panel p-6 rounded-xl relative hover:shadow-lg transition-all">
            <div className="absolute top-4 right-4 text-xs font-bold text-gray-400 border border-gray-200 px-2 py-1 rounded">
              DAY {post.day}
            </div>
            <h3 className="text-xl font-bold font-serif mb-3 pr-12 text-gray-900">{post.title}</h3>
            <div className="text-gray-700 text-sm leading-relaxed whitespace-pre-wrap font-sans">
              {post.content}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default CalendarView;